name: dartdosh
version: 0.6.4
description: A powerful Flutter build CLI tool with automatic version management, smart file naming, and personalized experience
repository: https://github.com/ahadjonovss/dartdosh
homepage: https://github.com/ahadjonovss/dartdosh
environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  dartdosh: dartdosh

dependencies:
  args: ^2.4.2
  yaml: ^3.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3